### PR TITLE
Fix migration command

### PR DESCRIPTION
**Pull request by Mdhesari**

### CODE REVIEW

**Comment by Mdhesari** [comment]
you can merge this pr to apply all recent changes

**Comment by reziamini** [comment]
No plan to change the PHP version to 8.
Please delete composer change and don't commit composer.

**Comment by Mdhesari** [comment]
You are using php 8 syntax and you don't have plan to use php 8

Funny

**Comment by reziamini** [comment]
@Mdhesari Could you please show me where PHP 8 has been used??
If it has been used, needs to be rolled back for L6, L7.

**Pull request closed without merging**
